x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8501"
    command:
      - streamlit
      - run
      - ./webui/Main.py
      - --server.address=0.0.0.0
      - --server.port=8501
      - --server.enableCORS=false
      - --server.enableXsrfProtection=false
      - --browser.gatherUsageStats=false
    restart: always
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "traefik.docker.network=coolify"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    command:
      - python3
      - main.py
    restart: always
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "traefik.docker.network=coolify"

networks:
  coolify:
    external: true
